"""Datasource for the JSON file generated by rpki_client."""

import asyncio
import base64
import logging
import os
from collections.abc import Generator
from datetime import datetime, timedelta, timezone
from ipaddress import ip_network
from typing import Any, Optional, TypedDict, override

import orjson
import xxhash

from pyrtr.datasources.datasource import (
    ASPA,
    ROA,
    BGPSecFilter,
    BGPSecKey,
    PrefixFilter,
    RPKIData,
    RPKIDatasource,
    Serialized,
    SLURMDatasource,
)
from pyrtr.kvdb import KVDB, KVDBView

logger = logging.getLogger(__name__)


class JSONMetadata(TypedDict):
    """File metadata"""

    buildmachine: str
    buildtime: str
    elapsedtime: int
    usertime: int
    systemtime: int
    roas: int
    failedroas: int
    invalidroas: int
    aspas: int
    failedaspas: int
    invalidaspas: int
    bgpsec_pubkeys: int
    certificates: int
    invalidcertificates: int
    nonfunctionalcas: int
    taks: int
    tals: int
    invalidtals: int
    talfiles: list[str]
    manifests: int
    failedmanifests: int
    crls: int
    gbrs: int
    repositories: int
    vrps: int
    uniquevrps: int
    vsps: int
    uniquevsps: int
    vaps: int
    uniquevaps: int
    cachedir_new_files: int
    cachedir_del_files: int
    cachedir_del_dirs: int
    cachedir_superfluous_files: int
    cachedir_del_superfluous_files: int


class NonFuncCA(TypedDict):
    """Non functional CA"""

    location: str
    ta: str
    caRepository: str
    rpkiManifest: str
    ski: str


class JSONROA(TypedDict):
    """
    Internal contstruct that represents RPKI ROAs and SLURM Prefix Assertions.

    Keys:
    -----
    asn: int
        The ASN of the ROA
    prefix: str
        The prefix of the ROA
    maxLength: int
        The maximum prefix length of the ROA
    ta: str
        The Trust Anchor of the ROA.
    expires: str
        The unix timestamp of when the ROA expires.
    """

    asn: int
    prefix: str
    maxLength: int
    ta: str
    expires: int


class JSONBGPSecKey(TypedDict):
    """
    Internal construct that represents RPKI BGPSec keys and SLURM BGPSec Key Assertions.

    Keys:
    -----
    asn: int
        The ASN of the BGPSec Key
    ski: str
        The Subject Key Identifier of the BGPSec Key
    pubkey: str
        The Subject Public Key Info of the BGPSec Key, encoded in base64
    ta: str
        The Trust Anchor of the BGPSec Key.
    expires: int
        The unix timestamp of when the BGPSec Key expires.
    """

    asn: int
    ski: str
    pubkey: str
    ta: Optional[str]
    expires: int


class JSONFile(TypedDict):
    """Defines the fields in the JSON file"""

    metadata: JSONMetadata
    roas: list[JSONROA]
    bgpsec_keys: list[JSONBGPSecKey]
    nonfunc_cas: list[NonFuncCA]
    aspas: list[ASPA]
    path: os.PathLike[str] | str


class JSONContent(TypedDict):
    """Defines the keys and values for the content field"""

    metadata: JSONMetadata
    db_path: os.PathLike[str] | str


class JSON(RPKIData):
    """Extends the RPKIData structure setting the content key to JSONContent"""

    content: JSONContent


class RPKIClient(RPKIDatasource):
    """
    Interface for the JSON file as generated by rpki_client.
    """

    def __init__(
        self,
        *,
        version: int,
        data_location: str | os.PathLike[str],
        cache_location: str | os.PathLike[str],
        slurm: Optional[SLURMDatasource] = None,
        expire: int = 7200,
        encryption_key: Optional[bytes] | None = None,
    ):
        """
        Arguments:
        ----------
        version: int
            The RTR version number
        data_location: str | os.PathLike[str]
            The path for the RPKI-Client JSON file
        cache_location: str | os.PathLike[str]
            The path for the cache directory
        slurm: Optional[SLURMDatasource] = None
            The SLURM data source. Default: None
        expire: int
            The RTR expire time
        encryption_key: Optional[bytes] | None = None
            The encryption key for the database
        """
        super().__init__(
            version=version,
            data_location=data_location,
            cache_location=cache_location,
            expire=expire,
            slurm=slurm,
        )

        try:
            os.mkdir(self.cache_location)
        except FileExistsError:
            pass
        self.snapshots: dict[int, JSON] = {}
        if encryption_key is None:
            encryption_key = b""
            logger.warning("No encryption key provided for RPKIClient. Using empty key.")
        self.encryption_key = encryption_key

    def _calculate_roa_diffs(
        self, old_roas: dict[bytes, ROA], new_roas: dict[bytes, ROA]
    ) -> Generator[tuple[bytes, bytes], Any, Any]:
        """
        Calculates the differences in the ROAs between the old and the new snapshort and yields
        prefix PDUs.

        Arguments:
        ----------
        old_roas: dict[str, ROA]
            ROAs in the old JSON file
        new_roas: dict[str, ROA]
            ROAs in the new JSON file

        Returns:
        --------
        Generator[bytes]: Yields serialized prefix PDUs
        """
        # Generate hashabale data structures
        old_roas_keys: set[bytes] = set(old_roas.keys())
        new_roas_keys: set[bytes] = set(new_roas.keys())

        # Yield changes
        added_roa_keys: set[bytes] = new_roas_keys - old_roas_keys
        for key in added_roa_keys:
            new_roa = new_roas[key]
            yield key, self.serialize_prefix(
                new_roa["prefix"], new_roa["asn"], new_roa["maxLength"], 1
            )

        removed_roa_keys: set[bytes] = old_roas_keys - new_roas_keys
        for key in removed_roa_keys:
            old_roa = old_roas[key]
            yield key, self.serialize_prefix(
                old_roa["prefix"], old_roa["asn"], old_roa["maxLength"], 0
            )

    def _calculate_bgpsec_key_diffs(
        self,
        old_bgpsec_keys: dict[bytes, BGPSecKey],
        new_bgpsec_keys: dict[bytes, BGPSecKey],
    ) -> Generator[tuple[bytes, bytes], Any, Any]:
        """
        Calculates the differences in the BGPSec Keys between the old and the new JSON file and
        yields prefix PDUs.

        Arguments:
        ----------
        old_bgpsec_keys: dict[str, BGPSecKey]
            BGPSec Keys in the old JSON file
        new_bgpsec_keys: dict[str, BGPSecKey]
            BGPSec Keys in the new JSON file

        Returns:
        --------
        Generator[bytes]: Yields serialized router key PDUs
        """
        # Generate hashabale data structures
        old_bgpsec_key_keys: set[bytes] = set(old_bgpsec_keys.keys())
        new_bgpsec_key_keys: set[bytes] = set(new_bgpsec_keys.keys())

        # Yield changes
        added_bgpsec_key_keys: set[bytes] = new_bgpsec_key_keys - old_bgpsec_key_keys
        for key in added_bgpsec_key_keys:
            new_bgpsec_key = new_bgpsec_keys[key]
            # This is not stated anywhere in the rpki-client docs
            ski = base64.b16decode(new_bgpsec_key["ski"], casefold=True)
            # This is not stated anywhere in the rpki-client docs
            pubkey = base64.b64decode(new_bgpsec_key["pubkey"])
            yield key, self.serialize_router_key(new_bgpsec_key["asn"], ski, pubkey, 1)

        removed_bgpsec_key_keys: set[bytes] = old_bgpsec_key_keys - new_bgpsec_key_keys
        for key in removed_bgpsec_key_keys:
            old_bgpsec_key = old_bgpsec_keys[key]
            # This is not stated anywhere in the rpki-client docs
            ski = base64.b16decode(old_bgpsec_key["ski"], casefold=True)
            # This is not stated anywhere in the rpki-client docs
            pubkey = base64.b64decode(old_bgpsec_key["pubkey"])
            yield key, self.serialize_router_key(old_bgpsec_key["asn"], ski, pubkey, 0)

    def _calculate_data_diffs(
        self,
        new_snapshot_db_path: os.PathLike[str] | str,
        old_snapshot_db_path: os.PathLike[str] | str,
    ) -> Serialized:
        """
        Calculates the differences in the data between the old and the new JSON file and returns
        the serialized diffs according to RTRv0.

        Arguments:
        ----------
        new_snapshot_db_path: os.PathLike[str] | str
            Path to the DB containing the new snapshot
        old_snapshot_db_path: os.PathLike[str] | str
            Path to the DB containing the old snapshot

        Returns:
        --------
        Serialized: The serialized diffs.
        """

        match self.version:
            case 0:
                # Update the snapshot
                return self._calculate_data_diffs_v0(new_snapshot_db_path, old_snapshot_db_path)
            case 1:
                # Update the snapshot
                return self._calculate_data_diffs_v1(new_snapshot_db_path, old_snapshot_db_path)
            case _:
                raise ValueError(f"Unsupported version number: {self.version}")

    def _calculate_data_diffs_v0(
        self,
        new_snapshot_db_path: os.PathLike[str] | str,
        old_snapshot_db_path: os.PathLike[str] | str,
    ) -> Serialized:
        """
        Calculates the differences in the data between the old and the new JSON file and returns
        the serialized diffs according to RTRv0.

        Arguments:
        ----------
        new_snapshot_db_path: os.PathLike[str] | str
            Path to the DB containing the new snapshot
        old_snapshot_db_path: os.PathLike[str] | str
            Path to the DB containing the old snapshot

        Returns:
        --------
        Serialized: The serialized diffs.
        """

        # Read ROAs from disk
        new_roas = {
            key: ROA(
                asn=value["asn"],
                prefix=value["prefix"],
                ta=value["ta"],
                maxLength=value["maxLength"],
                expires=value["expires"],
            )
            for key, value in KVDB(
                db_path=new_snapshot_db_path, table="roas_", encryption_key=self.encryption_key
            ).items()
        }
        old_roas = {
            key: ROA(
                asn=value["asn"],
                prefix=value["prefix"],
                ta=value["ta"],
                maxLength=value["maxLength"],
                expires=value["expires"],
            )
            for key, value in KVDB(
                db_path=old_snapshot_db_path, table="roas_", encryption_key=self.encryption_key
            ).items()
        }

        # Calculate ROA diffs
        vrps = self._calculate_roa_diffs(old_roas=old_roas, new_roas=new_roas)

        # Save new diffs to disk
        with KVDB(
            db_path=old_snapshot_db_path, table="vrp_diffs_", encryption_key=self.encryption_key
        ) as vrp_diffs:
            for key, value in vrps:
                vrp_diffs[key] = value

        return {
            "vrps": KVDBView(vrp_diffs.db_path, vrp_diffs.table, self.encryption_key),
            "router_keys": [],
        }

    def _calculate_data_diffs_v1(
        self,
        new_snapshot_db_path: os.PathLike[str] | str,
        old_snapshot_db_path: os.PathLike[str] | str,
    ) -> Serialized:
        """
        Calculates the differences in the data between the old and the new JSON file and returns
        the serialized diffs according to RTRv1.

        Arguments:
        ----------
        new_snapshot_db_path: os.PathLike[str] | str
            Path to the DB containing the new snapshot
        old_snapshot_db_path: os.PathLike[str] | str
            Path to the DB containing the old snapshot

        Returns:
        --------
        Serialized: The serialized diffs.
        """

        # Read ROAs from disk
        new_roas = {
            key: ROA(
                asn=value["asn"],
                prefix=value["prefix"],
                ta=value["ta"],
                maxLength=value["maxLength"],
                expires=value["expires"],
            )
            for key, value in KVDB(
                db_path=new_snapshot_db_path, table="roas_", encryption_key=self.encryption_key
            ).items()
        }
        old_roas = {
            key: ROA(
                asn=value["asn"],
                prefix=value["prefix"],
                ta=value["ta"],
                maxLength=value["maxLength"],
                expires=value["expires"],
            )
            for key, value in KVDB(
                db_path=old_snapshot_db_path, table="roas_", encryption_key=self.encryption_key
            ).items()
        }

        # Calculate ROA diffs
        vrps = self._calculate_roa_diffs(old_roas=old_roas, new_roas=new_roas)

        # Save new diffs to disk
        with KVDB(
            db_path=old_snapshot_db_path, table="vrp_diffs_", encryption_key=self.encryption_key
        ) as vrp_diffs:
            for key, value in vrps:
                vrp_diffs[key] = value

        # Read BGPSec Keys from disk
        new_bgpsec_keys = {
            key: BGPSecKey(
                asn=value["asn"],
                ski=value["ski"],
                pubkey=value["pubkey"],
                ta=value["ta"],
                expires=value["expires"],
            )
            for key, value in KVDB(
                db_path=new_snapshot_db_path,
                table="bgpsec_keys_",
                encryption_key=self.encryption_key,
            ).items()
        }
        old_bgpsec_keys = {
            key: BGPSecKey(
                asn=value["asn"],
                ski=value["ski"],
                pubkey=value["pubkey"],
                ta=value["ta"],
                expires=value["expires"],
            )
            for key, value in KVDB(
                db_path=old_snapshot_db_path,
                table="bgpsec_keys_",
                encryption_key=self.encryption_key,
            ).items()
        }

        # Calcuate BGPSec Keys diff
        router_keys = self._calculate_bgpsec_key_diffs(
            old_bgpsec_keys=old_bgpsec_keys,
            new_bgpsec_keys=new_bgpsec_keys,
        )

        # Write diffs to disk
        with KVDB(
            db_path=old_snapshot_db_path,
            table="router_key_diffs_",
            encryption_key=self.encryption_key,
        ) as router_key_diffs:
            for key, value in router_keys:
                router_key_diffs[key] = value

        return {
            "vrps": KVDBView(vrp_diffs.db_path, vrp_diffs.table, self.encryption_key),
            "router_keys": KVDBView(
                router_key_diffs.db_path, router_key_diffs.table, self.encryption_key
            ),
        }

    @staticmethod
    def _filter_roa(roa: ROA, slurm_prefix_filters: list[PrefixFilter]) -> bool:
        for prefix_filter in slurm_prefix_filters:
            if prefix_filter["prefix"] is None:
                if prefix_filter["asn"] == roa["asn"]:
                    # PrefixFilter {"asn": 64496, "prefix": null} matches all ROAs with ASN 64496
                    return True
            elif prefix_filter["asn"] is None:
                # PrefixFilter {"asn": null, "prefix": "2001:db8::/32"} matches all ROAs with prefix
                # 2001:db8::/32 and any ASN
                try:
                    return prefix_filter["prefix"].supernet_of(roa["prefix"])  # type: ignore
                except TypeError:
                    pass
            else:
                # PrefixFilter {"asn": 64496, "prefix": "2001:db8::/32"} matches all ROAs with ASN
                # 64496 and prefix 2001:db8::/32
                try:
                    if prefix_filter["asn"] == roa["asn"] and prefix_filter["prefix"].supernet_of(
                        roa["prefix"]  # type: ignore
                    ):
                        return True
                except TypeError:
                    pass

        return False

    @staticmethod
    def _filter_bgpsec_key(bgpsec_key: BGPSecKey, slurm_bgpsec_filters: list[BGPSecFilter]) -> bool:
        for bgpsec_filter in slurm_bgpsec_filters:
            if bgpsec_filter["ski"] is None:
                if bgpsec_filter["asn"] == bgpsec_key["asn"]:
                    # BGPSecFilter {"asn": 64496, "ski": null} matches all BGPSecKey with ASN 64496
                    return True
            elif bgpsec_filter["asn"] is None:
                # BGPSecFilter {"asn": null, "ski": "BE889B55D0B737397D75C49F485B858FA98AD11F"}
                # matches all BGPSecKey with SKI "BE889B55D0B737397D75C49F485B858FA98AD11F" and any
                # ASN
                try:
                    return bgpsec_filter["ski"] == bgpsec_key["ski"]
                except TypeError:
                    pass
            else:
                # BGPSecFilter {"asn": 64496, "ski": "BE889B55D0B737397D75C49F485B858FA98AD11F"}
                # matches all BGPSecKey with ASN 64496 and SKI
                # "BE889B55D0B737397D75C49F485B858FA98AD11F"
                try:
                    if (
                        bgpsec_filter["asn"] == bgpsec_key["asn"]
                        and bgpsec_filter["ski"] == bgpsec_key["ski"]
                    ):
                        return True
                except TypeError:
                    pass

        return False

    async def _reduce_roas(
        self,
        json_roas: list[JSONROA],
        slurm_roas: list[ROA],
        slurm_prefix_filters: list[PrefixFilter],
    ) -> dict[bytes, ROA]:
        """
        Reduces a list of JSONROAs into a dict of unique, filtered and valid ROAs.
        Every json_roa in `json_roas` that matches the filters in `slurm_prefix_filters` is
        discarded. `slurm_roas` are simply added to the output without filters.

        Arguments:
        ----------
        json_roas: list[JSONROA]
            The JSONROAs to reduce
        slurm_roas: list[ROA]
            The SLURM Prefix assertions to add to the list
        slurm_prefix_filter: list[PrefixFilter]
            The SLURM Prefix Filter used to filter the `roas`

        Returns:
        --------
        dict[bytes, ROA]: The reduced ROAs
        """
        current_timestamp = datetime.now(timezone.utc).timestamp()

        reduced_roas: dict[bytes, ROA] = {}
        for json_roa in json_roas:
            if current_timestamp >= json_roa["expires"]:
                continue

            roa: ROA = {
                "asn": json_roa["asn"],
                "expires": json_roa["expires"],
                "maxLength": json_roa["maxLength"],
                "ta": json_roa["ta"],
                "prefix": ip_network(json_roa["prefix"]),
            }

            if self._filter_roa(roa, slurm_prefix_filters):
                continue

            key = f'{roa["asn"]}|{roa["prefix"]}|{roa["maxLength"]}'.encode("utf-8")
            reduced_roas[key] = roa
            await asyncio.sleep(0)

        for roa in slurm_roas:
            key = (f'{roa["asn"]}|{roa["prefix"]}|{roa["maxLength"]}').encode("utf-8")
            reduced_roas[key] = roa
            await asyncio.sleep(0)

        return reduced_roas

    async def _reduce_bgpsec_keys(
        self,
        json_bgpsec_keys: list[JSONBGPSecKey],
        slurm_bgpsec_keys: list[BGPSecKey],
        slurm_bgpsec_filters: list[BGPSecFilter],
    ) -> dict[bytes, BGPSecKey]:
        """
        Reduces a list of JSONBGPSecKey Keys into a dict of unique, filtered and valid BGPSecKeys.
        Every json_bgpsec_key in `json_bgpsec_key` that matches the filters in
        `slurm_bgpsec_keys_filters` is discarded. `slurm_bgpsec_keys` are simply added to the output
        without filters.

        Arguments:
        ----------
        json_bgpsec_keys: list[JSONBGPSecKey]
            The BGPSec Keys to reduce
        slurm_bgpsec_keys: list[BGPSecKey]
            The SLURM BGPSec assertions to add to the list
        slurm_bgpsec_filters: list[BGPSecFilter]
            The SLURM BGPSec Filter used to filter the `bgpsec_keys`

        Returns:
        --------
        dict[str, BGPSecKey]: The reduced BGPSec Keys
        """
        current_timestamp = datetime.now(timezone.utc).timestamp()

        reduced_bgpsec_keys: dict[bytes, BGPSecKey] = {}
        for json_bgpsec_key in json_bgpsec_keys:
            if current_timestamp >= json_bgpsec_key["expires"]:
                continue

            bgpsec_key: BGPSecKey = {
                "asn": json_bgpsec_key["asn"],
                "expires": json_bgpsec_key["expires"],
                "ta": json_bgpsec_key["ta"],
                # This is not stated anywhere in the rpki-client docs
                "ski": base64.b16decode(json_bgpsec_key["ski"], casefold=True),
                # This is not stated anywhere in the rpki-client docs
                "pubkey": base64.b64decode(json_bgpsec_key["pubkey"]),
            }

            if self._filter_bgpsec_key(bgpsec_key, slurm_bgpsec_filters):
                continue

            key = (
                f"{bgpsec_key["asn"]}|"
                f"{json_bgpsec_key["ski"].upper()}|"
                f"{json_bgpsec_key["pubkey"].upper()}"
            ).encode("utf-8")
            reduced_bgpsec_keys[key] = bgpsec_key

            await asyncio.sleep(0)

        for bgpsec_key in slurm_bgpsec_keys:
            key = b"|".join(
                [str(bgpsec_key["asn"]).encode("utf-8"), bgpsec_key["ski"], bgpsec_key["pubkey"]]
            )
            reduced_bgpsec_keys[key] = bgpsec_key
            await asyncio.sleep(0)

        return reduced_bgpsec_keys

    async def _reduce_objects(
        self,
        *,
        json_roas: list[JSONROA],
        slurm_roas: list[ROA],
        slurm_prefix_filters: list[PrefixFilter],
        json_bgpsec_keys: list[JSONBGPSecKey],
        slurm_bgpsec_keys: list[BGPSecKey],
        slurm_bgpsec_filters: list[BGPSecFilter],
    ) -> tuple[dict[bytes, ROA], dict[bytes, BGPSecKey]]:
        match self.version:
            case 0:
                # Parse ROAs and do not parse BGPSec Keys
                roas = await self._reduce_roas(
                    json_roas,
                    slurm_roas,
                    slurm_prefix_filters,
                )
                bgpsec_keys = {}
            case 1:
                # Parse ROAs
                roas = await self._reduce_roas(json_roas, slurm_roas, slurm_prefix_filters)
                # Parse BGPSec Keys
                bgpsec_keys = await self._reduce_bgpsec_keys(
                    json_bgpsec_keys, slurm_bgpsec_keys, slurm_bgpsec_filters
                )
            case _:
                raise ValueError(f"Unsupported version number: {self.version}")

        return (roas, bgpsec_keys)

    @override
    async def parse(self) -> JSON:
        """
        Loads the content of the file ignoring expired and filtered ROAs and BGPSec Keys

        Returns:
        --------
        JSON: The JSON file
        """
        logger.debug("Parsing the RPKI JSON file")

        # Read the JSON file
        data: bytes = await self.read_json_file()
        json_file: JSONFile = orjson.loads(data)  # pylint: disable=no-member

        # Check if the file is expired
        buildtime = datetime.fromisoformat(json_file["metadata"]["buildtime"])
        expire_moment = buildtime + timedelta(seconds=self.expire)

        # Generate the database path string
        db_name: str = f'{json_file["metadata"]["buildmachine"]}_{int(buildtime.timestamp())}'
        db_path: str = os.path.join(self.cache_location, f"db_{db_name}_v{self.version}.sqlite")

        if os.path.exists(db_path):
            raise FileExistsError("The RPKI database file already exists")

        # Set values baseline
        roas: dict[bytes, ROA] = {}
        bgpsec_keys: dict[bytes, BGPSecKey] = {}
        aspas: dict[bytes, ASPA] = {}

        # Parse values
        if datetime.now(timezone.utc) > expire_moment:
            # The file is expired and so are VRPs, BGPSec Keys and ASPAs
            logger.warning("The JSON file is expired")
        else:
            # Load SLURM data if available
            slurm_roas: list[ROA] = []
            slurm_prefix_filters: list[PrefixFilter] = []
            if self.slurm is not None and hasattr(self.slurm, "roas"):
                slurm_roas = list(self.slurm.roas)
                slurm_prefix_filters = list(self.slurm.prefix_filters)

            slurm_bgpsec_keys: list[BGPSecKey] = []
            slurm_bgpsec_filters: list[BGPSecFilter] = []
            if self.slurm is not None and hasattr(self.slurm, "bgpsec_keys"):
                slurm_bgpsec_keys = list(self.slurm.bgpsec_keys)
                slurm_bgpsec_filters = list(self.slurm.bgpsec_filters)

            roas, bgpsec_keys = await self._reduce_objects(
                json_roas=json_file["roas"],
                slurm_roas=slurm_roas,
                slurm_prefix_filters=slurm_prefix_filters,
                json_bgpsec_keys=json_file["bgpsec_keys"],
                slurm_bgpsec_keys=slurm_bgpsec_keys,
                slurm_bgpsec_filters=slurm_bgpsec_filters,
            )

        # Calculate hash
        json_hash: str = xxhash.xxh64(
            bytes().join(roas.keys())
            + bytes().join(bgpsec_keys.keys())
            + bytes().join(aspas.keys())
        ).hexdigest()

        # Write VRPs
        with KVDB(db_path=db_path, table="vrps_", encryption_key=self.encryption_key) as vrps_db:
            vrps_db.create_table()
            try:
                vrps_db.begin()
                for key, roa in roas.items():
                    vrp = self.serialize_prefix(roa["prefix"], roa["asn"], roa["maxLength"], 1)
                    vrps_db[key] = vrp
                    await asyncio.sleep(0)
            finally:
                vrps_db.commit()

        # Write ROAs
        with KVDB(db_path=db_path, table="roas_", encryption_key=self.encryption_key) as roas_db:
            roas_db.create_table()
            try:
                roas_db.begin()
                for key, roa in roas.items():
                    roas_db[key] = roa
                    await asyncio.sleep(0)
            finally:
                roas_db.commit()

        # Write Router Keys
        with KVDB(
            db_path=db_path, table="router_keys_", encryption_key=self.encryption_key
        ) as router_keys_db:
            router_keys_db.create_table()
            try:
                router_keys_db.begin()
                for key, bgpsec_key in bgpsec_keys.items():
                    router_key = self.serialize_router_key(
                        bgpsec_key["asn"], bgpsec_key["ski"], bgpsec_key["pubkey"], 1
                    )
                    router_keys_db[key] = router_key
                    await asyncio.sleep(0)
            finally:
                router_keys_db.commit()

        # Write BGPSec Keys
        with KVDB(
            db_path=db_path, table="bgpsec_keys_", encryption_key=self.encryption_key
        ) as bgpsec_keys_db:
            bgpsec_keys_db.create_table()
            try:
                bgpsec_keys_db.begin()
                for key, bgpsec_key in bgpsec_keys.items():
                    bgpsec_keys_db[key] = bgpsec_key
                    await asyncio.sleep(0)
            finally:
                bgpsec_keys_db.close()

        return {
            "content": {
                "metadata": json_file["metadata"],
                "db_path": db_path,
            },
            "hash": json_hash,
            "timestamp": buildtime.timestamp(),
            "diffs": {"vrps": [], "router_keys": []},
            "serialized": {
                "vrps": KVDBView(vrps_db.db_path, vrps_db.table, self.encryption_key),
                "router_keys": KVDBView(
                    router_keys_db.db_path, router_keys_db.table, self.encryption_key
                ),
            },
        }

    @override
    async def reload(self) -> bool:
        """
        Purges stale snapshorts, load the new one, calculate diffs, and increment serial.

        Return:
        -------
        bool: True if the process completed successfully.
        """
        logger.debug("Reloading the RPKI datasource for V%d", self.version)

        # Delete stale snapshots
        await self.purge()

        # Read the JSON file
        try:
            new_snapshot: JSON = await self.parse()
        except FileExistsError:
            return False
        except (orjson.JSONDecodeError, KeyError) as error:  # pylint: disable=no-member
            raise ValueError(f"Unable to load the file: {error}") from error

        # Check if the new and the current most recent snapshots are the same
        try:
            if new_snapshot["hash"] == self.snapshots[self.serial]["hash"]:
                # Delete new database
                try:
                    KVDB(
                        db_path=new_snapshot["content"]["db_path"],
                        table="",
                        encryption_key=self.encryption_key,
                    ).purge()
                except (FileExistsError, FileNotFoundError):
                    pass

                return False
        except KeyError:
            pass

        # Calculate diffs
        for old_snapshot in self.snapshots.values():
            # Update the snapshot
            old_snapshot["diffs"] = self._calculate_data_diffs(
                new_snapshot["content"]["db_path"], old_snapshot["content"]["db_path"]
            )

        # `self.serial` is a property that only returns the `max()`` key in `self.snapthosts`,
        # so adding a new key to snapshots, also increases serial.
        self.snapshots[self.serial + 1] = new_snapshot
        self.last_update = new_snapshot["content"]["metadata"]["buildtime"]

        logger.info("Serial for V%d changed to: %d", self.version, self.serial)

        return True

    @override
    async def purge(self) -> None:
        # Cleanup stale snapshots
        self.snapshots = {
            serial: snapshot
            for serial, snapshot in self.snapshots.items()
            if snapshot["timestamp"] > datetime.now(timezone.utc).timestamp() - self.expire
        }

        # Remove orphaned databases
        for file in os.scandir(self.cache_location):
            for snapshot in self.snapshots.values():
                if os.path.basename(snapshot["content"]["db_path"]) in file.name:
                    break
            else:
                if (
                    os.path.isfile(file)
                    and file.name.startswith("db_")
                    and file.name.endswith(f"_v{self.version}.sqlite")
                ):
                    db_path = os.path.join(self.cache_location, file.name)
                    for filename in KVDB(
                        db_path=db_path, table="", encryption_key=self.encryption_key
                    ).purge():
                        logger.debug("Purging file from cache: %s", filename)

            await asyncio.sleep(0)
