"""Interface towards the rpki-client JSON file"""

import asyncio
import base64
import logging
import os
from collections.abc import Generator
from datetime import datetime, timedelta, timezone
from typing import Any, TypedDict, override
from urllib.parse import urlparse

import aiofiles
import aiohttp
import orjson
import xxhash

from pyrtr.datasources.datasource import Data, Datasource
from pyrtr.datasources.rpki_client.kvdb import KVDB, KVDBView

logger = logging.getLogger(__name__)


class JSONMetadata(TypedDict):
    """File metadata"""

    buildmachine: str
    buildtime: str
    elapsedtime: int
    usertime: int
    systemtime: int
    roas: int
    failedroas: int
    invalidroas: int
    aspas: int
    failedaspas: int
    invalidaspas: int
    bgpsec_pubkeys: int
    certificates: int
    invalidcertificates: int
    nonfunctionalcas: int
    taks: int
    tals: int
    invalidtals: int
    talfiles: list[str]
    manifests: int
    failedmanifests: int
    crls: int
    gbrs: int
    repositories: int
    vrps: int
    uniquevrps: int
    vsps: int
    uniquevsps: int
    vaps: int
    uniquevaps: int
    cachedir_new_files: int
    cachedir_del_files: int
    cachedir_del_dirs: int
    cachedir_superfluous_files: int
    cachedir_del_superfluous_files: int


class ROA(TypedDict):
    """RPKI ROA"""

    asn: int
    prefix: str
    maxLength: int
    ta: str
    expires: int


class BGPSecKey(TypedDict):
    """BGPSec key"""

    asn: int
    ski: str
    pubkey: str
    ta: str
    expires: int


class NonFuncCA(TypedDict):
    """Non functional CA"""

    location: str
    ta: str
    caRepository: str
    rpkiManifest: str
    ski: str


class ASPA(TypedDict):
    """ASPA object"""

    customer_asid: int
    expires: int
    providers: list[int]


class JSONFile(TypedDict):
    """Defines the fields in the JSON file"""

    metadata: JSONMetadata
    roas: list[ROA]
    bgpsec_keys: list[BGPSecKey]
    nonfunc_cas: list[NonFuncCA]
    aspas: list[ASPA]
    path: os.PathLike[str] | str


class JSONContent(TypedDict):
    """Defines the keys and values in for the content field"""

    metadata: JSONMetadata
    db_path: os.PathLike[str] | str


class JSON(Data):
    """Extends the Data structure setting the content key to JSONContent"""

    content: JSONContent


class RPKIClient(Datasource):
    """
    Interface for the JSON file as generated by rpki_client.
    """

    def __init__(
        self,
        version: int,
        data_location: str | os.PathLike[str],
        cache_location: str | os.PathLike[str],
        expire: int = 7200,
    ):
        """
        Arguments:
        ----------
        version: int
            The RTR version number
        data_location: str | os.PathLike[str]
            The path for the RPKI-Client JSON file
        cache_location: str | os.PathLike[str]
            The path for the cache directory
        expire: int
            The RTR expire time
        """
        super().__init__(version, data_location, cache_location, expire)

        try:
            os.mkdir(self.cache_location)
        except FileExistsError:
            pass
        self.snapshots: dict[int, JSON] = {}

    async def _read_json_file(self) -> bytes:
        """
        Reads the JSON file either locally or remotely if self.location is a URL

        Returns:
        --------
        bytes: The content of the JSON file
        """
        try:
            # Test if the `location` is a URL
            urlparse(self.data_location)
            async with aiohttp.ClientSession() as session:
                async with session.get(self.data_location) as response:
                    return (await response.text()).encode("utf-8")
        except ValueError:
            async with aiofiles.open(self.data_location, mode="rb") as file:
                return await file.read()

    def _calculate_roa_diffs(
        self, old_roas: dict[bytes, ROA], new_roas: dict[bytes, ROA]
    ) -> Generator[tuple[bytes, bytes], Any, Any]:
        """
        Calculates the differences in the ROAs between the old and the new JSON file and yields
        prefix PDUs.

        Arguments:
        ----------
        old_roas: dict[str, ROA]
            ROAs in the old JSON file
        new_roas: dict[str, ROA]
            ROAs in the new JSON file

        Returns:
        --------
        Generator[bytes]: Yields serialized prefix PDUs
        """
        # Generate hashabale data structures
        old_roas_keys: set[bytes] = set(old_roas.keys())
        new_roas_keys: set[bytes] = set(new_roas.keys())

        # Yield changes
        added_roa_keys: set[bytes] = new_roas_keys - old_roas_keys
        for key in added_roa_keys:
            new_roa = new_roas[key]
            yield key, self.serialize_prefix(
                new_roa["prefix"], new_roa["asn"], new_roa["maxLength"], 1
            )

        removed_roa_keys: set[bytes] = old_roas_keys - new_roas_keys
        for key in removed_roa_keys:
            old_roa = old_roas[key]
            yield key, self.serialize_prefix(
                old_roa["prefix"], old_roa["asn"], old_roa["maxLength"], 0
            )

    def _calculate_bgpsec_key_diffs(
        self,
        old_bgpsec_keys: dict[bytes, BGPSecKey],
        new_bgpsec_keys: dict[bytes, BGPSecKey],
    ) -> Generator[tuple[bytes, bytes], Any, Any]:
        """
        Calculates the differences in the BGPSec Keys between the old and the new JSON file and
        yields prefix PDUs.

        Arguments:
        ----------
        old_bgpsec_keys: dict[str, BGPSecKey]
            BGPSec Keys in the old JSON file
        new_bgpsec_keys: dict[str, BGPSecKey]
            BGPSec Keys in the new JSON file

        Returns:
        --------
        Generator[bytes]: Yields serialized router key PDUs
        """
        # Generate hashabale data structures
        old_bgpsec_key_keys: set[bytes] = set(old_bgpsec_keys.keys())
        new_bgpsec_key_keys: set[bytes] = set(new_bgpsec_keys.keys())

        # Yield changes
        added_bgpsec_key_keys: set[bytes] = new_bgpsec_key_keys - old_bgpsec_key_keys
        for key in added_bgpsec_key_keys:
            new_bgpsec_key = old_bgpsec_keys[key]
            # This is not stated anywhere in the rpki-client docs
            ski = base64.b16decode(new_bgpsec_key["ski"], casefold=True)
            # This is not stated anywhere in the rpki-client docs
            pubkey = base64.b64decode(new_bgpsec_key["pubkey"])
            yield key, self.serialize_router_key(new_bgpsec_key["asn"], ski, pubkey, 1)

        removed_bgpsec_key_keys: set[bytes] = old_bgpsec_key_keys - new_bgpsec_key_keys
        for key in removed_bgpsec_key_keys:
            old_bgpsec_key = old_bgpsec_keys[key]
            # This is not stated anywhere in the rpki-client docs
            ski = base64.b16decode(old_bgpsec_key["ski"], casefold=True)
            # This is not stated anywhere in the rpki-client docs
            pubkey = base64.b64decode(old_bgpsec_key["pubkey"])
            yield key, self.serialize_router_key(old_bgpsec_key["asn"], ski, pubkey, 0)

    async def _reduce_roas(self, roas: list[ROA]) -> dict[bytes, ROA]:
        """
        Reduces a list of ROAs into a dict of unique and valid ROAs.

        Arguments:
        ----------
        roas: list[ROA]
            The ROAs to reduce

        Returns:
        --------
        dict[str, ROA]: The reduced ROAs
        """
        current_timestamp = datetime.now(timezone.utc).timestamp()

        reduced_roas: dict[bytes, ROA] = {}
        for roa in roas:
            if current_timestamp >= roa["expires"]:
                continue
            key = f'{roa["asn"]}|{roa["prefix"]}|{roa["maxLength"]}'.encode("utf-8")
            reduced_roas[key] = roa
            await asyncio.sleep(0)

        return reduced_roas

    async def _reduce_bgpsec_keys(self, bgpsec_keys: list[BGPSecKey]) -> dict[bytes, BGPSecKey]:
        """
        Reduces a list of BGPSec Keys into a dict of unique and valid BGPSec Keys.

        Arguments:
        ----------
        roas: list[BGPSecKey]
            The BGPSec Keys to reduce

        Returns:
        --------
        dict[str, BGPSecKey]: The reduced BGPSec Keys
        """
        current_timestamp = datetime.now(timezone.utc).timestamp()

        reduced_bgpsec_keys: dict[bytes, BGPSecKey] = {}
        for bgpsec_key in bgpsec_keys:
            if current_timestamp >= bgpsec_key["expires"]:
                continue
            key = f'{bgpsec_key["asn"]}|{bgpsec_key["ski"]}|{bgpsec_key["pubkey"]}'.encode("utf-8")
            reduced_bgpsec_keys[key] = bgpsec_key
            await asyncio.sleep(0)

        return reduced_bgpsec_keys

    @override
    async def parse(self) -> JSON:
        """
        Loads the content of the file. Remove expired ROAs and BGPSec Keys

        Returns:
        --------
        JSON: The JSON file
        """
        logger.debug("Parsing the JSON file")

        # Read the JSON file
        data: bytes = await self._read_json_file()
        json_file: JSONFile = orjson.loads(data)  # pylint: disable=no-member

        # Check if the file is expired
        buildtime = datetime.fromisoformat(json_file["metadata"]["buildtime"])
        expire_moment = buildtime + timedelta(seconds=self.expire)

        # Generate the database path string
        db_name: str = f'{json_file["metadata"]["buildmachine"]}_{int(buildtime.timestamp())}'
        db_path: str = os.path.join(self.cache_location, f"db_{db_name}_v{self.version}.sqlite")

        if os.path.exists(db_path):
            raise FileExistsError("The database file already exists")

        # Set values baseline
        roas: dict[bytes, ROA] = {}
        bgpsec_keys: dict[bytes, BGPSecKey] = {}
        aspas: dict[bytes, ASPA] = {}

        # Parse values
        if datetime.now(timezone.utc) > expire_moment:
            # The file is expired and so are VRPs, BGPSec Keys and ASPAs
            logger.warning("The JSON file is expired")
        else:
            match self.version:
                case 0:
                    # Parse ROAs and do not parse BGPSec Keys
                    roas = await self._reduce_roas(json_file["roas"])
                case 1:
                    # Parse ROAs
                    roas = await self._reduce_roas(json_file["roas"])
                    # Parse BGPSec Keys
                    bgpsec_keys = await self._reduce_bgpsec_keys(json_file["bgpsec_keys"])
                case _:
                    raise ValueError(f"Unsupported version number: {self.version}")

        # Calculate hash
        json_hash: str = xxhash.xxh64(
            bytes().join(roas.keys())
            + bytes().join(bgpsec_keys.keys())
            + bytes().join(aspas.keys())
        ).hexdigest()

        # Write full dumps
        with KVDB(db_path=db_path, table="vrps_") as vrps_db:
            vrps_db.create_table()
            try:
                vrps_db.begin()
                for key, roa in roas.items():
                    vrp = self.serialize_prefix(roa["prefix"], roa["asn"], roa["maxLength"], 1)
                    vrps_db[key] = vrp
                    await asyncio.sleep(0)
            finally:
                vrps_db.commit()

        with KVDB(db_path=db_path, table="roas_") as roas_db:
            roas_db.create_table()
            try:
                roas_db.begin()
                for key, roa in roas.items():
                    roas_db[key] = roa
                    await asyncio.sleep(0)
            finally:
                roas_db.commit()

        with KVDB(db_path=db_path, table="router_keys_") as router_keys_db:
            router_keys_db.create_table()
            try:
                router_keys_db.begin()
                for key, bgpsec_key in bgpsec_keys.items():
                    # This is not stated anywhere in the rpki-client docs
                    ski = base64.b16decode(bgpsec_key["ski"], casefold=True)
                    # This is not stated anywhere in the rpki-client docs
                    pubkey = base64.b64decode(bgpsec_key["pubkey"])
                    router_key = self.serialize_router_key(bgpsec_key["asn"], ski, pubkey, 1)
                    router_keys_db[key] = router_key
                    await asyncio.sleep(0)
            finally:
                router_keys_db.commit()

        with KVDB(db_path=db_path, table="bgpsec_keys_") as bgpsec_keys_db:
            bgpsec_keys_db.create_table()
            try:
                bgpsec_keys_db.begin()
                for key, bgpsec_key in bgpsec_keys.items():
                    bgpsec_keys_db[key] = bgpsec_key
                    await asyncio.sleep(0)
            finally:
                bgpsec_keys_db.close()

        return {
            "content": {
                "metadata": json_file["metadata"],
                "db_path": db_path,
            },
            "hash": json_hash,
            "timestamp": buildtime.timestamp(),
            "diffs": {"vrps": [], "router_keys": []},
            "serialized": {
                "vrps": KVDBView(vrps_db.db_path, vrps_db.table),
                "router_keys": KVDBView(router_keys_db.db_path, router_keys_db.table),
            },
        }

    @override
    async def reload(self) -> bool:
        """
        Purge old JSON files, load the new one, calculate diffs, and increment serial.

        Return:
        -------
        bool: True if the process completed successfully.
        """
        logger.debug("Reloading the datasource for V%d", self.version)

        # Delete stale snapshots
        await self.purge()

        # Read the JSON file
        try:
            new_snapshot: JSON = await self.parse()
        except FileExistsError:
            return False
        except (orjson.JSONDecodeError, KeyError) as error:  # pylint: disable=no-member
            raise ValueError(f"Unable to load the file: {error}") from error

        # Check if the new and the current JSON are the same
        try:
            if new_snapshot["hash"] == self.snapshots[self.serial]["hash"]:
                # Delete new database
                try:
                    KVDB(db_path=new_snapshot["content"]["db_path"], table="").purge()
                except (FileExistsError, FileNotFoundError):
                    pass

                return False
        except KeyError:
            pass

        # Calculate diffs
        for old_snapshot in self.snapshots.values():
            # Do not waste CPU cycles if not needed
            match self.version:
                case 0:
                    new_roas = {
                        key: ROA(value)
                        for key, value in KVDB(
                            db_path=new_snapshot["content"]["db_path"], table="roas_"
                        ).items()
                    }
                    old_roas = {
                        key: ROA(value)
                        for key, value in KVDB(
                            db_path=old_snapshot["content"]["db_path"], table="roas_"
                        ).items()
                    }
                    vrps = self._calculate_roa_diffs(new_roas=new_roas, old_roas=old_roas)

                    with KVDB(
                        db_path=old_snapshot["content"]["db_path"], table="vrp_diffs_"
                    ) as vrp_diffs:
                        for key, value in vrps:
                            vrp_diffs[key] = value

                    old_snapshot["diffs"] = {
                        "vrps": KVDBView(vrp_diffs.db_path, vrp_diffs.table),
                        "router_keys": [],
                    }
                case 1:
                    new_roas = {
                        key: ROA(value)
                        for key, value in KVDB(
                            db_path=new_snapshot["content"]["db_path"], table="roas_"
                        ).items()
                    }
                    old_roas = {
                        key: ROA(value)
                        for key, value in KVDB(
                            db_path=old_snapshot["content"]["db_path"], table="roas_"
                        ).items()
                    }
                    vrps = self._calculate_roa_diffs(new_roas=new_roas, old_roas=old_roas)

                    with KVDB(
                        db_path=old_snapshot["content"]["db_path"], table="vrp_diffs_"
                    ) as vrp_diffs:
                        for key, value in vrps:
                            vrp_diffs[key] = value

                    new_bgpsec_keys = {
                        key: BGPSecKey(value)
                        for key, value in KVDB(
                            db_path=new_snapshot["content"]["db_path"], table="bgpsec_keys_"
                        ).items()
                    }
                    old_bgpsec_keys = {
                        key: BGPSecKey(value)
                        for key, value in KVDB(
                            db_path=old_snapshot["content"]["db_path"], table="bgpsec_keys_"
                        ).items()
                    }
                    router_keys = self._calculate_bgpsec_key_diffs(
                        new_bgpsec_keys=new_bgpsec_keys,
                        old_bgpsec_keys=old_bgpsec_keys,
                    )

                    with KVDB(
                        db_path=old_snapshot["content"]["db_path"], table="router_key_diffs_"
                    ) as router_key_diffs:
                        for key, value in router_keys:
                            router_key_diffs[key] = value

                    old_snapshot["diffs"] = {
                        "vrps": KVDBView(vrp_diffs.db_path, vrp_diffs.table),
                        "router_keys": KVDBView(router_key_diffs.db_path, router_key_diffs.table),
                    }
                case _:
                    raise ValueError(f"Unsupported version number: {self.version}")

        # Serial is a property that only returns the max() key in self.snapthosts,
        # so adding a new key in snapshots, also increases serial.
        self.snapshots[self.serial + 1] = new_snapshot
        self.last_update = new_snapshot["content"]["metadata"]["buildtime"]

        logger.info("Serial for V%d changed to: %d", self.version, self.serial)

        return True

    @override
    async def purge(self) -> None:
        # Cleanup stale snapshots
        self.snapshots = {
            serial: snapshot
            for serial, snapshot in self.snapshots.items()
            if snapshot["timestamp"] > datetime.now(timezone.utc).timestamp() - self.expire
        }

        # Remove orphaned databases
        if not self.serial:
            for file in os.scandir(self.cache_location):
                if (
                    os.path.isfile(file)
                    and file.name.startswith("db_")
                    and file.name.endswith(f"_v{self.version}.sqlite")
                ):
                    db_path = os.path.join(self.cache_location, file.name)
                    for filename in KVDB(db_path=db_path, table="").purge():
                        logger.debug("Purging file from cache: %s", filename)
        else:
            for file in os.scandir(self.cache_location):
                for snapshot in self.snapshots.values():
                    if os.path.basename(snapshot["content"]["db_path"]) in file.name:
                        break
                else:
                    if (
                        os.path.isfile(file)
                        and file.name.startswith("db_")
                        and file.name.endswith("_v{self.version}.sqlite")
                    ):
                        for filename in KVDB(db_path=file.name, table="").purge():
                            logger.debug("Purging file from cache: %s", filename)
