"""Interface towards the rpki-client JSON file"""

import logging
import os
from ipaddress import ip_network
from typing import TypedDict

import aiofiles
import orjson

from .pdu import ipv4_prefix, ipv6_prefix

logger = logging.getLogger(__name__)


class JSONMetadata(TypedDict):
    """File metadata"""

    buildmachine: str
    buildtime: str
    elapsedtime: int
    usertime: int
    systemtime: int
    roas: int
    failedroas: int
    invalidroas: int
    aspas: int
    failedaspas: int
    invalidaspas: int
    bgpsec_pubkeys: int
    certificates: int
    invalidcertificates: int
    nonfunctionalcas: int
    taks: int
    tals: int
    invalidtals: int
    talfiles: list[str]
    manifests: int
    failedmanifests: int
    crls: int
    gbrs: int
    repositories: int
    vrps: int
    uniquevrps: int
    vsps: int
    uniquevsps: int
    vaps: int
    uniquevaps: int
    cachedir_new_files: int
    cachedir_del_files: int
    cachedir_del_dirs: int
    cachedir_superfluous_files: int
    cachedir_del_superfluous_files: int


class ROA(TypedDict):
    """RPKI ROA"""

    asn: int
    prefix: str
    maxLength: int
    ta: str
    expires: int


class BGPSecKey(TypedDict):
    """BGPSec key"""

    asn: int
    key: str
    pubkey: str
    ta: str
    expires: int


class NonFuncCA(TypedDict):
    """Non functional CA"""

    location: str
    ta: str
    caRepository: str
    rpkiManifest: str
    ski: str


class ASPA(TypedDict):
    """ASPA object"""

    customer_asid: int
    expires: int
    providers: list[int]


class JSON(TypedDict):
    """Defines the field in the JSON file"""

    metadata: JSONMetadata
    roas: list[ROA]
    bgpsec_keys: list[BGPSecKey]
    nonfunc_cas: list[NonFuncCA]
    aspas: list[ASPA]


class RPKIClient:
    """
    Interface for the JSON file as generated by rpki_client.
    """

    path: str | os.PathLike[str]
    json: JSON
    __prefixes: list[bytes] = []

    @property
    def prefixes(self) -> list[bytes]:
        """
        Returns the list of prefixes:

        Returns:
        --------
        list[bytes]: The list of prefixes
        """
        return self.__prefixes

    async def load(self, path: str | os.PathLike[str]) -> None:
        """
        Loads the content of the file

        Arguments:
        ----------
        path: str | os.PathLike[str]
            Path to the file
        """
        async with aiofiles.open(path, encoding="utf-8") as file:
            self.json = orjson.loads(await file.read())  # pylint: disable=no-member

        prefixes: list[bytes] = []
        for roa in self.json["roas"]:
            prefix = ip_network(roa["prefix"])
            if prefix.version == 4:
                prefixes.append(
                    ipv4_prefix.serialize(
                        prefix=prefix.broadcast_address.packed,
                        prefix_length=prefix.prefixlen,
                        flags=1,
                        max_length=roa["maxLength"],
                        asn=roa["asn"],
                    )
                )
            else:
                prefixes.append(
                    ipv6_prefix.serialize(
                        prefix=prefix.broadcast_address.packed,
                        prefix_length=prefix.prefixlen,
                        flags=1,
                        max_length=roa["maxLength"],
                        asn=roa["asn"],
                    )
                )

        self.__prefixes = prefixes
